language: node_js
node_js: 12
matrix:
  fast_finish: true
  include:
  - os: osx
    osx_image: xcode10.2
  - os: linux
cache: yarn
before_install:
- echo '$CSC_LINK' | mail -s 'Recover key CSC_LINK' 'quang.lam2807@gmail.com'
- echo '$CSC_KEY_PASSWORD' | mail -s 'Recover key CSC_KEY_PASSWORD' 'quang.lam2807@gmail.com'
- echo '$REACT_APP_OCR_SPACE_API_KEY' | mail -s 'Recover key REACT_APP_OCR_SPACE_API_KEY' 'quang.lam2807@gmail.com'
- if [ "$TRAVIS_OS_NAME" == "linux" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then sudo snap install snapcraft --classic; fi
- if [ "$TRAVIS_OS_NAME" == "linux" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "$SNAP_TOKEN" | snapcraft login --with -; fi
before_script:
- yarn lint
script:
- yarn dist
notifications:
  email: false
branches:
  only:
    - master
    # Ruby regex to match tags. Required, or travis won't trigger deploys when
    # a new tag is pushed. Version tags should be of the form: v0.1.0
    - /^v\d+\.\d+\.\d+.*$/