# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Atomery
description: We build products that make your life simpler and more productive.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://atomery.com" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /blog/:title
excerpt_separator: <!--more-->
highlighter: rouge
feed:
  path: /blog/atom.xml

webcatalog_version: 24.8.0
juli_version_prerelease: 10.0.0-beta.2
juli_version: 9.8.0
singlebox_version: 9.8.0
switchbar_version: 0.2.0
translatium_version: 13.8.2

pagination:
  enabled: true

collections:
  catalog_apps:
    output: true
    permalink: /webcatalog/catalog/:path/

defaults:
  - scope:
      path: ""
      type: "catalog_apps"
    values:
      layout: "catalog-app"
      app_id: "webcatalog"

markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate-v2

google_analytics: UA-159584254-2
fastspring_account_id: webcatalog

exclude:
  - yarn.lock
  - package.json
  - scripts

include:
  - _redirects
